[package]
name = "easy_orm"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.39.1", features = ["full"] }
